namespace Client.Targeting
{
    using System;

    public enum TargetAction
    {
        Agility = 8,
        ArchCure = 0x18,
        ArchProtection = 0x19,
        Bandage = 0x3e8,
        Bless = 0x10,
        BloodOath = 0x65,
        Bola = 0x7d0,
        ChainLightning = 0x30,
        CleanseFire = 200,
        CloseWounds = 0xc9,
        Clumsy = 0,
        CorpseSkin = 0x66,
        Cunning = 9,
        Cure = 10,
        Curse = 0x1a,
        DetectHidden = 0xbb8,
        Discord = 0x7d1,
        Dispel = 40,
        EnergyBolt = 0x29,
        EnergyField = 0x31,
        EvilOmen = 0x68,
        Explosion = 0x2a,
        Feeblemind = 2,
        Fireball = 0x11,
        FireField = 0x1b,
        FlameStrike = 50,
        GreaterHeal = 0x1c,
        Harm = 11,
        Heal = 3,
        Invisibility = 0x2b,
        Lightning = 0x1d,
        MagicArrow = 4,
        ManaDrain = 30,
        ManaVampire = 0x34,
        MassCurse = 0x2d,
        MeteorSwarm = 0x36,
        MindBlast = 0x24,
        MindRot = 0x6b,
        PainSpike = 0x6c,
        Paralyze = 0x25,
        ParalyzeField = 0x2e,
        Poison = 0x13,
        PoisonField = 0x26,
        PoisonStrike = 0x6d,
        RemoveCurse = 0xd0,
        Resurrection = 0x3a,
        Reveal = 0x2f,
        Strangle = 110,
        Strength = 15,
        Unknown = -1,
        VengeSpirit = 0x71,
        WallOfStone = 0x17,
        Weaken = 7
    }
}

